name: 'Tests the application Code and uploads the results'
description: 'composite run action'

inputs:
  JAVA_VERSION_TO_INSTALL:
    required: true
    type: string
    description: 'Java version to be installed'
  UPLOADED_ARTIFACTS_DIR:
    required: true
    type: string
    description: 'Uploads artifacts directory'
  RUN_UNIT_TESTS:
    required: true
    type: boolean
    description: 'Run unit tests if `TRUE`, else integration tests'

runs:
  using: "composite"
  steps:
    - name: 'Set up the Oracle JDK `${{ inputs.JAVA_VERSION_TO_INSTALL }}`'
      uses: './.github/actions/install-java'
      with:
        JAVA_VERSION_TO_INSTALL: ${{ inputs.JAVA_VERSION_TO_INSTALL }}
    - name: 'Runs the unit tests'
      if: ${{ RUN_UNIT_TESTS == TRUE }}
      run: mvn -Djacoco.haltOnFailure=false test --file pom.xml
    - name: 'Runs the integration tests'
      if: ${{ RUN_UNIT_TESTS != TRUE }}
      run: mvn -Dskip.ut=true -Djacoco.haltOnFailure=false verify --file pom.xml
    - name: 'Uploads the results to ${{ inputs.UPLOADED_ARTIFACTS_DIR }} folder'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.UPLOADED_ARTIFACTS_DIR }}
        retention-days: 1
        path: |
          target/