name: 'Tests the application Code and uploads the results'
description: 'composite run action'

inputs:
  JAVA_VERSION_TO_INSTALL:
    required: true
    type: string
    description: 'Java version to be installed'
  UPLOADED_ARTIFACTS_DIR:
    required: true
    type: string
    description: 'Uploads artifacts directory'
  RUN_UNIT_TESTS:
    required: true
    type: boolean
    description: 'Run unit tests if `TRUE`, else integration tests'

runs:
  using: "composite"
  steps:
    - name: 'Set up the Oracle JDK `${{ inputs.JAVA_VERSION_TO_INSTALL }}`'
      uses: './.github/actions/install-java'
      with:
        JAVA_VERSION_TO_INSTALL: ${{ inputs.JAVA_VERSION_TO_INSTALL }}
    - name: 'Runs the unit tests'
      if: ${{ inputs.RUN_UNIT_TESTS == 'true' }}
      run: mvn -Djacoco.haltOnFailure=false test --file pom.xml
      shell: bash
    - name: 'Runs the integration tests'
      if: ${{ inputs.RUN_UNIT_TESTS == 'false' }}
      run: mvn -Dskip.ut=true -Djacoco.haltOnFailure=false verify --file pom.xml
      shell: bash
    - name: 'Set environment variables'
      run: |
        echo "UPLOAD_DIR=${{ inputs.UPLOADED_ARTIFACTS_DIR }}-${{ inputs.RUN_UNIT_TESTS == 'true' && 'ut' || 'it' }}" >> $GITHUB_ENV
        echo "FILES_DIR_PREFIX=${{ inputs.RUN_UNIT_TESTS == 'true' && 'unit' || 'integration' }}" >> $GITHUB_ENV
      shell: bash
    - name: '${{ env.FILES_DIR_PREFIX }}-tests'' Summary'
      if: always()
      uses: test-summary/action@v2
      with:
        show: "all"
        paths: "target/site/${{ env.FILES_DIR_PREFIX }}-tests/**/TEST-*.xml"
    - name: 'Uploads the results to ${{ env.UPLOAD_DIR }} folder'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.UPLOAD_DIR }}
        retention-days: 1
        path: |
          target