name: 'Setup GitHub Runner with Java and application Code'
on:
  workflow_call:
    inputs:
      JAVA_VERSION_TO_INSTALL:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up the Oracle JDK 20'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20