name: 'CI/CD'
on: push
env:
  JAVA_VERSION: 20
  SETUP_GH_RUNNER_WITH_JAVA: ${{ github.repository }}/.github/workflows/setup-gh-runner-with-java.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-gh-runner-with-java.yml
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Compiles the application code'
        run: mvn clean compile --file pom.xml
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: ${{ env.JAVA_VERSION }}
      - name: 'Runs the unit tests to test the application code'
        run: mvn test --file pom.xml
  deploy:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: ${{ env.JAVA_VERSION }}
      - name: 'Packaging the application and generating the project site'
        run: mvn --batch-mode --update-snapshots -DskipTests clean package site --file pom.xml
      - name: 'Install gh-pages'
        run: npm i gh-pages
      - name: 'Deploy with gh-pages'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          mkdir /tmp/gh-pages
          cp README.md /tmp/gh-pages
          cp -r target/site /tmp/gh-pages/site
          cp target/*-SNAPSHOT*.jar* /tmp/gh-pages
          npx gh-pages --dist /tmp/gh-pages -u "github-actions-bot <support+actions@github.com>"
          rm -rf /tmp/gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}