name: 'JAVA CI/CD'
on: push
env:
  JAVA_VERSION: 20
  UPLOADED_ARTIFACTS_DIR: 'gh-pages'

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      JAVA_VERSION: ${{steps.setup-env.outputs.JAVA_VERSION}}
    steps:
      - name: 'Setup Environment'
        id: setup-env
        run: |
          echo "JAVA_VERSION=${{ env.JAVA_VERSION }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Compiles the application code'
        run: mvn clean compile --file pom.xml

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Runs the unit tests and uploads the results'
        uses: './.github/actions/run-tests-and-upload-results'
        with:
          RUN_UNIT_TESTS: true
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Runs the integration tests and uploads the results'
        uses: './.github/actions/run-tests-and-upload-results'
        with:
          RUN_UNIT_TESTS: false
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  generate-coverage-report:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Generates the code coverage report'
        uses: './.github/actions/generate-reports'
        with:
          ACTION_NAME: "GENERATE-COVERAGE-REPORT"
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  generate-tests-report:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Generates the tests report'
        uses: './.github/actions/generate-reports'
        with:
          ACTION_NAME: "GENERATE-TESTS-REPORT"
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  generate-project-site:
    runs-on: ubuntu-latest
    needs:
      - generate-tests-report
      - generate-coverage-report

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Generates the project''s site'
        uses: './.github/actions/generate-reports'
        with:
          ACTION_NAME: "GENERATE-PROJECT-SITE"
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  deploy-to-gh-pages:
    needs: generate-project-site
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Packaging the application'
        run: mvn --batch-mode --update-snapshots -DskipTests package --file pom.xml #TODO: upload the artifacts in the test job and then clean package
      - name: 'Upload required files to `${{ env.UPLOADED_ARTIFACTS_DIR }}` folder'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.UPLOADED_ARTIFACTS_DIR }}
          retention-days: 1
          path: |
            README.md
            target/site
            target/surefire-reports
            target/*-SNAPSHOT*.jar*
      - name: 'Download the uploaded artifacts to `${{ env.UPLOADED_ARTIFACTS_DIR }}` folder'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.UPLOADED_ARTIFACTS_DIR }}
          path: ${{ env.UPLOADED_ARTIFACTS_DIR }}
      - name: 'Deploy to GitHub Pages'
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.UPLOADED_ARTIFACTS_DIR }}
  deploy-to-gh-packages:
    needs:
     - setup-env
     - unit-tests
     - integration-tests
    permissions:
      contents: read
      packages: write
    uses: './.github/workflows/deploy.yml'
    with:
      JAVA_VERSION_TO_INSTALL: ${{ needs.setup-env.outputs.JAVA_VERSION }}