name: Builds and Tests the Java Spring Boot Application
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the UserCRUDWithJWT repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK 20'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20
      - name: 'Builds the application code'
        run: mvn clean package
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the UserCRUDWithJWT repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK 20'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20
      - name: 'Runs the unit tests to test the application code'
        run: mvn test