name: 'CI/CD'
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK 20'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20
          cache: maven
      - name: 'Compiles the application code'
        run: mvn -B clean compile --file pom.xml
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK 20'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20
          cache: maven
      - name: 'Runs the unit tests to test the application code'
        run: mvn -B test --file pom.xml