name: 'JAVA CI/CD'
on: push
env:
  JAVA_VERSION: 20
  UPLOADED_ARTIFACTS_DIR: 'gh-pages'
  BRANCHES_COVERAGE_THRESHOLD: '60%'
  INSTRUCTIONS_COVERAGE_THRESHOLD: '60%'

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      JAVA_VERSION: ${{steps.setup-env.outputs.JAVA_VERSION}}
    steps:
      - name: 'Setup Environment'
        id: setup-env
        run: |
          echo "JAVA_VERSION=${{ env.JAVA_VERSION }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Compiles the application code'
        run: mvn clean compile --file pom.xml

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Runs the unit tests and uploads the results'
        uses: './.github/actions/run-tests-and-upload-results'
        with:
          RUN_UNIT_TESTS: true
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Runs the integration tests and uploads the results'
        uses: './.github/actions/run-tests-and-upload-results'
        with:
          RUN_UNIT_TESTS: false
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

#  generate-code-coverage-badge:
#    if: ${{ github.ref == 'refs/heads/master' }}
#    runs-on: ubuntu-latest
#    needs: generate-coverage-report
#
#    steps:
#      - name: 'Download the uploaded artifacts to `${{ env.UPLOADED_ARTIFACTS_DIR }}` folder'
#        uses: actions/download-artifact@v3
#        with:
#          name: ${{ env.UPLOADED_ARTIFACTS_DIR }}
#          path: ${{ env.UPLOADED_ARTIFACTS_DIR }}
#      - name: 'Generate and upload JaCoCo Code Coverage Badge'
#        id: jacoco
#        uses: cicirello/jacoco-badge-generator@v2
#        with:
#          generate-branches-badge: true
#          fail-if-branches-less-than: ${{ env.BRANCHES_COVERAGE_THRESHOLD }}
#          fail-if-coverage-less-than: ${{ env.INSTRUCTIONS_COVERAGE_THRESHOLD }}
#          badges-directory: './target/site/jacoco/jacoco-resources/badges'
#      - name: 'Log code coverage percentage'
#        run: |
#          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
#          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
#      - name: 'Upload JaCoCo code coverage badge'
#        uses: actions/upload-artifact@v2
#        with:
#          name: jacoco-report
#          path: target/site/jacoco/
#      - name: 'Upload JaCoCo code coverage badge to `${{ env.UPLOADED_ARTIFACTS_DIR }}` folder'
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.UPLOADED_ARTIFACTS_DIR }}
#          retention-days: 1
#          path: './target/site/jacoco/jacoco-resources/badges'
#
  generate-project-site:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Generates the project''s site'
        uses: './.github/actions/generate-reports'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}

  deploy-to-gh-pages:
    needs: generate-project-site
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Download the uploaded artifacts to `${{ env.UPLOADED_ARTIFACTS_DIR }}` folder'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.UPLOADED_ARTIFACTS_DIR }}
          path: ${{ env.UPLOADED_ARTIFACTS_DIR }}
      - name: 'Deploy to GitHub Pages'
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.UPLOADED_ARTIFACTS_DIR }}
  deploy-to-gh-packages:
    needs:
     - setup-env
     - unit-tests
     - integration-tests
    permissions:
      contents: read
      packages: write
    uses: './.github/workflows/deploy.yml'
    with:
      JAVA_VERSION_TO_INSTALL: ${{ needs.setup-env.outputs.JAVA_VERSION }}