name: 'Java Code Coverage'

on:
  push:
    branches: [ master ]
env:
  JAVA_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        run: mvn -B clean test jacoco:report --file pom.xml

      - name: 'Generate JaCoCo Code Coverage Badge'
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          colors: green yellow orange red
          intervals: 90 75 60
          badges-directory: './target/site/jacoco/jacoco-resources/badges'

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: 'Upload JaCoCo coverage report'
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/