name: 'Setup GitHub Runner with Java and application Code'
on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: ${{ JAVA_VERSION_TO_INSTALL }}