name: 'Site CI/CD'
on: push
env:
  JAVA_VERSION: 20
  UPLOADED_ARTIFACTS_DIR: 'gh-pages'
  SITE_DIR: 'gh-pages/site'
  MODULE_DIR: 'SiteGeneration'

jobs:
  generate-project-site:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Generates the project''s site'
        uses: './.github/actions/generate-reports'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}
          MODULE_DIR: ${{ env.MODULE_DIR }}

  deploy-to-gh-pages:
    needs: generate-project-site
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Deploy the project''s site to GitHub Pages'
        uses: './.github/actions/deploy-to-gh-pages'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
          UPLOADED_ARTIFACTS_DIR: ${{ env.UPLOADED_ARTIFACTS_DIR }}
          MODULE_DIR: ${{ env.MODULE_DIR }}
          SITE_DIR: ${{ env.SITE_DIR }}